/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LandingLayoutImport } from './routes/_landing/layout'
import { Route as LandingIndexImport } from './routes/_landing/index'
import { Route as LandingPreviewIndexImport } from './routes/_landing/preview.index'
import { Route as LandingPhotoboothIndexImport } from './routes/_landing/photobooth.index'
import { Route as LandingEditorIndexImport } from './routes/_landing/editor.index'

// Create/Update Routes

const LandingLayoutRoute = LandingLayoutImport.update({
  id: '/_landing',
  getParentRoute: () => rootRoute,
} as any)

const LandingIndexRoute = LandingIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingLayoutRoute,
} as any)

const LandingPreviewIndexRoute = LandingPreviewIndexImport.update({
  id: '/preview/',
  path: '/preview/',
  getParentRoute: () => LandingLayoutRoute,
} as any)

const LandingPhotoboothIndexRoute = LandingPhotoboothIndexImport.update({
  id: '/photobooth/',
  path: '/photobooth/',
  getParentRoute: () => LandingLayoutRoute,
} as any)

const LandingEditorIndexRoute = LandingEditorIndexImport.update({
  id: '/editor/',
  path: '/editor/',
  getParentRoute: () => LandingLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LandingLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexImport
      parentRoute: typeof LandingLayoutImport
    }
    '/_landing/editor/': {
      id: '/_landing/editor/'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof LandingEditorIndexImport
      parentRoute: typeof LandingLayoutImport
    }
    '/_landing/photobooth/': {
      id: '/_landing/photobooth/'
      path: '/photobooth'
      fullPath: '/photobooth'
      preLoaderRoute: typeof LandingPhotoboothIndexImport
      parentRoute: typeof LandingLayoutImport
    }
    '/_landing/preview/': {
      id: '/_landing/preview/'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof LandingPreviewIndexImport
      parentRoute: typeof LandingLayoutImport
    }
  }
}

// Create and export the route tree

interface LandingLayoutRouteChildren {
  LandingIndexRoute: typeof LandingIndexRoute
  LandingEditorIndexRoute: typeof LandingEditorIndexRoute
  LandingPhotoboothIndexRoute: typeof LandingPhotoboothIndexRoute
  LandingPreviewIndexRoute: typeof LandingPreviewIndexRoute
}

const LandingLayoutRouteChildren: LandingLayoutRouteChildren = {
  LandingIndexRoute: LandingIndexRoute,
  LandingEditorIndexRoute: LandingEditorIndexRoute,
  LandingPhotoboothIndexRoute: LandingPhotoboothIndexRoute,
  LandingPreviewIndexRoute: LandingPreviewIndexRoute,
}

const LandingLayoutRouteWithChildren = LandingLayoutRoute._addFileChildren(
  LandingLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof LandingLayoutRouteWithChildren
  '/': typeof LandingIndexRoute
  '/editor': typeof LandingEditorIndexRoute
  '/photobooth': typeof LandingPhotoboothIndexRoute
  '/preview': typeof LandingPreviewIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof LandingIndexRoute
  '/editor': typeof LandingEditorIndexRoute
  '/photobooth': typeof LandingPhotoboothIndexRoute
  '/preview': typeof LandingPreviewIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_landing': typeof LandingLayoutRouteWithChildren
  '/_landing/': typeof LandingIndexRoute
  '/_landing/editor/': typeof LandingEditorIndexRoute
  '/_landing/photobooth/': typeof LandingPhotoboothIndexRoute
  '/_landing/preview/': typeof LandingPreviewIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/' | '/editor' | '/photobooth' | '/preview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/editor' | '/photobooth' | '/preview'
  id:
    | '__root__'
    | '/_landing'
    | '/_landing/'
    | '/_landing/editor/'
    | '/_landing/photobooth/'
    | '/_landing/preview/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LandingLayoutRoute: typeof LandingLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LandingLayoutRoute: LandingLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_landing"
      ]
    },
    "/_landing": {
      "filePath": "_landing/layout.tsx",
      "children": [
        "/_landing/",
        "/_landing/editor/",
        "/_landing/photobooth/",
        "/_landing/preview/"
      ]
    },
    "/_landing/": {
      "filePath": "_landing/index.tsx",
      "parent": "/_landing"
    },
    "/_landing/editor/": {
      "filePath": "_landing/editor.index.tsx",
      "parent": "/_landing"
    },
    "/_landing/photobooth/": {
      "filePath": "_landing/photobooth.index.tsx",
      "parent": "/_landing"
    },
    "/_landing/preview/": {
      "filePath": "_landing/preview.index.tsx",
      "parent": "/_landing"
    }
  }
}
ROUTE_MANIFEST_END */
